default_install_hook_types:  [pre-commit, commit-msg]
repos:
  - repo: local
    hooks:
      - id: gitlint
        name: Gitlint
        entry: gitlint --msg-filename
        language: python
        stages: [commit-msg]