services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    env_file:
      - ../.env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGPORT=${DATABASE_PORT}
    volumes:
      - ./postgres:/var/lib/postgres