# Generated by Django 4.2.1 on 2023-05-26 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nome da categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Texto da opção de resposta')),
                ('answer', models.BooleanField(default=False, verbose_name='Resposta correta?')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='Texto da pergunta')),
                ('level', models.CharField(choices=[('1', 'Fácil'), ('2', 'Médio'), ('3', 'Difícil')], max_length=1, verbose_name='Nível da pergunta')),
                ('active', models.BooleanField(default=True, verbose_name='Pergunta está ativa?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.category', verbose_name='Categoria da pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Pontuação do usuário')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.question', verbose_name='Pergunta'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('level', models.CharField(choices=[('1', 'Fácil'), ('2', 'Médio'), ('3', 'Difícil')], max_length=1, verbose_name='Nível da pergunta')),
                ('categories', models.ManyToManyField(to='mainApp.category')),
                ('users', models.ManyToManyField(related_name='users_match', to='mainApp.userprofile')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_winner', to='mainApp.userprofile')),
            ],
        ),
    ]
