# Generated by Django 4.2.1 on 2023-05-29 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_category_options_alter_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='questions',
            field=models.ManyToManyField(to='mainApp.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='match_answer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainApp.match'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='level',
            field=models.CharField(choices=[('1', 'Fácil'), ('2', 'Médio'), ('3', 'Difícil')], max_length=1, verbose_name='Nível das perguntas'),
        ),
    ]
