# Generated by Django 4.2.1 on 2023-06-11 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_match_options_alter_match_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
