# Generated by Django 4.2.1 on 2023-09-05 00:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_match_end_date_alter_match_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.option'),
        ),
    ]
