# Generated by Django 4.2.1 on 2023-09-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_date_useranswer_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
